language: c

compiler:
  - clang
  - gcc

install:
  - sudo pip install pytest
  - sudo apt-get update
  - sudo apt-get install -y valgrind
  - curl -O -L http://zlib.net/zlib-1.2.8.tar.gz
  - tar zxf zlib-1.2.8.tar.gz
  - cd zlib-1.2.8
  - ./configure
  - make
  - sudo make install
  - cd ..

script:
  - CFLAGS=-Werror make
  - make test_functional
  - make test_unit
  - make test_valgrind
