# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: do_build
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ gfortran cmake subversion automake m4 wget
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_OPENSSL=ON -DTECA_SOURCE=develop -DCMAKE_INSTALL_PREFIX=`pwd`/../../sb-install ..
          make -j2 install
          
